# Very simple refactor comparison for the seed distribution

In [1]:
from cg import *

In [2]:
refactor_pre = '/home/glemieux/scratch/e3sm-cases/cross_grid_glemieux-koug.fates.lobata.E9f562b53ab-F8b0ed78c/run/lnd/'
refactor_post = '/home/glemieux/scratch/e3sm-cases/cross_grid_seed-refac_koug.fates.lobata.Edd70a2833e-Ffda77af5/run/lnd/'

In [3]:
numsites = 2
numsc = 13
numpft = 12
pftlist = [6,8,9]
# pftlist = [1,2,3]
pftname = ['Evergreen Shrub','Deciduous Shrub','Arctic C3 Grass']
pftcolor=['g','gold','b']

In [4]:
flist_pre = glob(refactor_pre+'*.nc')
flist_pre.sort()
flist_post = glob(refactor_post+'*.nc')
flist_post.sort()

In [6]:
FATES_VEGC_PF_pre = get_siteTS_pft(flist_pre,'FATES_VEGC_PF',pftlist,numsites)
SEEDS_IN_LOCAL_pre = get_siteTS_all(flist_pre,'FATES_SEEDS_IN_LOCAL_EL',numsites)
SEEDS_IN_EXTERN_pre = get_siteTS_all(flist_pre,'FATES_SEEDS_IN_EXTERN_EL',numsites)
NPP_SEED_pre = get_siteTS_pft_scpf(flist_pre,'FATES_SEED_ALLOC_SZPF',pftlist,numsites,numsc)

In [7]:
FATES_VEGC_PF_post = get_siteTS_pft(flist_post,'FATES_VEGC_PF',pftlist,numsites)
SEEDS_IN_LOCAL_post = get_siteTS_all(flist_post,'FATES_SEEDS_IN_LOCAL_EL',numsites)
SEEDS_IN_EXTERN_post = get_siteTS_all(flist_post,'FATES_SEEDS_IN_EXTERN_EL',numsites)
NPP_SEED_post = get_siteTS_pft_scpf(flist_post,'FATES_SEED_ALLOC_SZPF',pftlist,numsites,numsc)

In [8]:
SEEDS_IN_EXTERN_post

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [9]:
SEEDS_IN_EXTERN_pre

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [18]:
NPP_SEED_pre[0] - NPP_SEED_post[0]

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [6.8862786e-22, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

In [13]:
NPP_SEED_post

[array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.49505896e-12, 0.00000000e+00, 0.00000000e+00],
        [4.77780523e-11, 1.60423376e-11, 1.10026159e-12],
        [5.48994322e-11, 1.02479657e-10, 4.78882255e-12],
        [5.69782138e-11, 1.27365479e-10, 7.76062201e-12],
        [4.58503305e-11, 2.23608337e-11, 1.60872411e-12],
        [1.06815832e-11, 0.00000000e+00, 0.00000000e+00],
        [6.87446687e-18, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]),
 array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.7

In [31]:
np.shape(NPP_SEED_post[0])

(12, 3)

In [27]:
np.shape(SEEDS_IN_EXTERN_post)

(2, 12)

In [28]:
np.shape(SEEDS_IN_LOCAL_post)

(2, 12)

In [30]:
np.shape(FATES_VEGC_PF_pre[0])

(12, 3)

In [51]:
for i in range(2):
    diff1 = FATES_VEGC_PF_post[i] - FATES_VEGC_PF_post[i]
    diff2 = NPP_SEED_post[i] - NPP_SEED_pre[i]
    diff3 = SEEDS_IN_EXTERN_post[i] - SEEDS_IN_EXTERN_pre[i]
    diff4 = SEEDS_IN_LOCAL_post[i] - SEEDS_IN_LOCAL_pre[i]
    if np.sum(diff1) > 0.0:
        print("i: {}, diff1:{}".format(i,diff1))
    else:
        print("FATES_VEGC_PF match")
    if np.sum(diff2) > 0.0:
        print("i: {}, diff2:{}".format(i,diff2))
    else:
        print("NPP_SEED match")   
    if np.sum(diff3) > 0.0:
        print("i: {}, diff3:{}".format(i,diff3))
    else:
        print("SEEDS_IN_EXTERN match")   
    if np.sum(diff4) > 0.0:
        print("i: {}, diff4:{}".format(i,diff4))
    else:
        print("SEEDS_IN_LOCAL match")   
    print("\n")

FATES_VEGC_PF match
NPP_SEED match
SEEDS_IN_EXTERN match
SEEDS_IN_LOCAL match


FATES_VEGC_PF match
NPP_SEED match
SEEDS_IN_EXTERN match
i: 1, diff4:[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.38436947e-20 0.00000000e+00]


